---
title: "Academic Research"
output: html_document
---

<b>Postdoctoral surpervisor</b> <br>
[Nicholas Rivers](https://sites.google.com/site/nicholasjrivers/) <br>

<b>Ph.D. committee:</b> <br>
<div style="text-align: justify">
[Jason Garred](http://web5.uottawa.ca/www5/jasongarred/index.html) (co-supervisor) <br>
[Abel Brodeur](https://sites.google.com/site/abelbrodeur/home?authuser=0) (co-supervisor) <br>
[Carolyn Fischer](https://www.rff.org/people/carolyn-fischer/)<br>
[Anthony Heyes](https://anthonyheyes.wordpress.com/)<br>
[Maya Papineau](https://sites.google.com/site/mayapapineau/home)
</div>

## Submitted Papers



<font size="3">[<b>Climate Change and the Distribution of Agricultural Output </b>](https://osf.io/preprints/socarxiv/yxzfu/)</font> <br>
with [Francisco Costa](https://sites.google.com/site/fjmcosta/), [Jason Garred](http://web5.uottawa.ca/www5/jasongarred/index.html) and [Joao Paulo Pessoa](https://sites.google.com/site/joaopaulocnpessoa/). __JOB MARKET PAPER__<br>
`Prediction` `Risk` `Uncertainty` `Climate Change` `Theory`

<div style="text-align: justify">Climate change may affect farmers not only by altering the expected productivity
of each crop they grow, but also by changing the year-to-year volatility of their output.
This paper uses a multi-run climate projection model to examine the potential impact
of climate change on the distribution of agricultural outcomes in India. Our analysis
suggests that the negative impact of the evolving climate on the mean may present a
more urgent problem than changes in yield variability. Previously rare weather draws
resulting in poor agricultural outcomes (1-in-100 years) are projected to become the
norm, increasing by 53 to 88 percentage points by the end of the 21st century. As a
result, we predict that Indian farmers will face a 16% to 33% decline in mean agricultural
revenue over the course of the century. Analysis using a structural general equilibrium
model with portfolio choice suggests consequences of a similar magnitude for welfare</div>
<br>

<font size="3">[<b>When are Tariff Cuts Not Enough? Heterogeneous Effects of Trade Preferences for the Least Developed Countries</b>](http://web5.uottawa.ca/www5/jasongarred/ForgeGarredKwon2021.pdf)</font> <br>
with [Jason Garred](http://web5.uottawa.ca/www5/jasongarred/index.html) and Kyae Lim Kwon <br>
`Causal inference` `Data Mining` `Trade` 

<div style="text-align: justify">
Poor countries export a remarkably narrow range of products.  To what extent have trade preferences targeted to the least developed countries (LDCs) changed this situation?  We study a large set of recent reforms to the LDC trade preferences offered by OECD countries.  Leveraging trade policy variation by importer, exporter, product and year, we show that tariff reductions have increased the prevalence of positive trade flows.  However, new flows have been far more likely to emerge in cases with previous 'export experience', i.e.\ where countries already exported the same product to another OECD country, or exported a related product to the same importer.  So this wave of tariff cuts for LDCs has resulted in an extension of existing patterns of trade rather than wider export diversification.

 </div>
<br>

<font size="3">[<b>CCTs and Fertility: Long-Term Impacts Across Two Generations</b>](CCTs_and_Fertility__Long_Term_Impacts_Across_Two_Generations_JHR.pdf)</font> <br>
`Causal inference` `Policy evaluation` `Health` `Theory`

<div style="text-align: justify">The Mexican conditional cash transfer program Progresa, started in 1997, has been found to have positively impacted many aspects of the lives of the poor in Mexico both in the short and long run. The few studies that used the initial randomization over the first 18 to 24 months failed to observe any change in fertility decisions. Using the IPUMS census survey, I construct two cohorts of women that I observe in 2010, 13 years after the program started. The older cohort mainly benefited from a reduction in the cost of quality of their children, while the younger cohort benefited, in addition, from a schooling treatment on themselves. The results from a difference-in-difference identification strategy suggest a significant negative effect on fertility in a fashion consistent with what Becker’s quality-quantity trade-off model predicts. Although, both cohorts reduced their fertility, no additional effect was found on the fertility of the younger cohort in the early part of their fertility window </div> <br>


## Work in Progress

<font size="3">[<b>High Temperatures and Vulnerabilities</b>]()</font> <br>
with [Nicholas Rivers](https://sites.google.com/site/nicholasjrivers/) <br>
`Climate Change` `Machine Learning`  

<div style="text-align: justify">
We examine the effect of high temperatures on individual income and document some of the determinants explaining heterogeneous effects. Using the longitudinal administrative survey of Canada, which contains information on 20\% of Canadian tax payers, we document that high temperatures, which are rare events, do not impact aggregate measures of income. The results change when including individual fixed-effects and suggests than a day with average temperature above 30 degrees is associated with a decrease in income by 1.5\% and an increase in health spending by 0.1\%. A decomposition of this effect suggests that it is mainly driven by the sectors of construction and retail.

<font size="3">[<b>Reactive or proactive? Capturing adaptation to climate change using machine learning</b>]()</font> <br>
with [Julia Mink](https://julia-thompson.github.io/Julia-Mink/) <br>
`Machine Learning` `Behavior` `Theory` `Adaptation` `Climate Change`

<div style="text-align: justify">
We study the determinants of climate change adaptation using both machine learning and economic theory. For farmers, crop choice is one of the most effective and cheapest way of mitigating the effects of climate change. Yet it is unclear whether farmers’ adapt in reaction to past weather realisations or in anticipation of climate change. 
We attempt to answer this question by testing two theories: one in which farmers are only backward looking and a second in which they are also forward looking. Since these two behavioural models do not live in the same parameter space, we follow Fudenberg et al. (2020) and measure how ‘\textit{complete}’ each theory is by comparing their predictive performance to a predictive upper bound defined using machine learning. Our results suggest that behavioural models assuming no adaption best describe the data.


<font size="3">[<b>US-China Trade Relationship and US pollution emission</b>]()</font> <br>
`Causal inference` `Trade` `Pollution` <br>
<div style="text-align: justify">
After being the champion of trade liberalization, the United States reversed its policy and engaged in protectionist measures particularly targeted at China. Since 2000, the Chinese import competition has significantly influenced the US industrial composition and motivated the 2018 US tariff increase. This paper takes advantage of these diametrically-opposed trade shocks to look at their impact on pollution emissions (CO, NO2, O3, PM10, PM2.5) in the US. First, I empirically examine how US counties have changed their pollution emissions in response to i) a fall in Chinese import prices and ii) recent protectionist measures and retaliatory tariffs. The reduced form identification relies on a weighted average of local exposure to Chinese competition in which weights are determined by counties' industrial composition prior to the shocks. Second, I decompose changes in pollution emissions among the different channels that may be impacted by these shocks. Specifically, in response to changes in comparative advantages, counties may change their levels of economic activity (scale), their type of activities (composition) and the pollution intensity of their production (technique).



